### ISSUE TITLE
yaml

### ISSUE THREAD

**Issue by jostylr** [jostylr/literate-programming-cli#6]
Thinking about adding yaml processing with a flag. In particular, the front block of a program could contain data that could be accessible to the program. 

```
---
title: Awesome
author: jostylr
---

# Some code

Just some code. run with -y?

    _"g:title" 
    _"g:author"    


```

**Comment by jostylr** [comment]
Should also support having three dots instead of dashes at the end of the yaml block. 

The 3 dashes at the bottom is a bit problematic in markdown because of it becoming a header, so perhaps the dots should be favored for this mechanism. We could scan for blocks surrounded by three dashes at the top and three dashes at the bottom. 

Should make sure the following works fine: 

```yaml
---
title:  'This is the title: it contains a colon'
author:
- Author One
- Author Two
tags: [nothing, nothingness]
abstract: |
  This is the abstract.

  It consists of two paragraphs.
...
```
This would be very hackish and definitely behind a command line flag/lprc.js setting. In particular, such a block in a code fence with the intention of escaping the block would not work though indenting would. 

It would also have problems with just three dashes being used. Maybe with the flag, it just is a syntax to not use except in connection with starting a yaml block. We could scan for three dots after that, but blank lines could be an issue.

Also note that there should be a code fence type of yaml which could exclude the separators or not. Yaml itself has syntax which will clash with markdown rendering if not escaped.
